package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * Created by Andrei on 23/04/2017.
 */
public class AdaugaProdus extends JFrame {
    private JPanel panelPrincipal;
    private JTextField descriereField;
    private JTextField pretField;
    private JButton adaugaProdusButton;
    private JTextField cantitateField;

    public AdaugaProdus() {
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setSize(380, 350);
        this.setLocationRelativeTo(null);
        this.setContentPane(panelPrincipal);

        //actualizareDateButton.addActionListener(new DateClient.ButonActualizareDate());

        this.setResizable(false);
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public JTextField getDescriereField() {
        return descriereField;
    }

    public JTextField getPretField() {
        return pretField;
    }

    public JButton getAdaugaProdusButton() {
        return adaugaProdusButton;
    }

    public JTextField getCantitateField() {
        return cantitateField;
    }


    public void setAdaugaProdusButton(ActionListener e) {
        adaugaProdusButton.addActionListener(e);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(4, 2, new Insets(20, 10, 20, 10), 10, -1));
        panelPrincipal.setBackground(new Color(-5404120));
        panelPrincipal.setMinimumSize(new Dimension(420, 350));
        panel1.add(panelPrincipal, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        descriereField = new JTextField();
        descriereField.setEditable(true);
        panelPrincipal.add(descriereField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(500, 200), 0, false));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("Comic Sans MS", label1.getFont().getStyle(), 16));
        label1.setText("Descriere");
        panelPrincipal.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 20), new Dimension(200, 20), 0, false));
        final JLabel label2 = new JLabel();
        label2.setFont(new Font("Comic Sans MS", label2.getFont().getStyle(), 16));
        label2.setText("Pret");
        panelPrincipal.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 20), new Dimension(200, 20), 0, false));
        pretField = new JTextField();
        panelPrincipal.add(pretField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(500, 200), 0, false));
        adaugaProdusButton = new JButton();
        adaugaProdusButton.setBackground(new Color(-11225979));
        adaugaProdusButton.setFont(new Font("Constantia", adaugaProdusButton.getFont().getStyle(), 14));
        adaugaProdusButton.setHorizontalAlignment(0);
        adaugaProdusButton.setHorizontalTextPosition(0);
        adaugaProdusButton.setText("Adauga produs");
        panelPrincipal.add(adaugaProdusButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_SOUTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(130, 20), new Dimension(300, 40), 0, false));
        final JLabel label3 = new JLabel();
        label3.setFont(new Font("Comic Sans MS", label3.getFont().getStyle(), 16));
        label3.setText("Cantitate");
        panelPrincipal.add(label3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 20), new Dimension(200, 20), 0, false));
        cantitateField = new JTextField();
        panelPrincipal.add(cantitateField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(500, 200), 0, false));
    }
}




