package presentation;

import bll.ProdusBLL;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Created by Andrei on 21/04/2017.
 */
public class ListaProduse extends JFrame {
    private JTable table1;
    private JPanel panel1;
    private JScrollPane ScrollPane;
    private JButton adaugaInCosButton;
    private JTextField idField;
    private JTextField cantitateField;
    private MyModel model;

    public ListaProduse() {
        model = new MyModel();
        table1 = new JTable();
        $$$setupUI$$$();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setSize(380, 350);

        this.setLocationRelativeTo(null);
        this.setContentPane(panel1);
        this.setSize(600, 400);
        //adaugaInCosButton.addActionListener(new ButonAdaugaInCos());


        this.setResizable(false);
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here

        table1 = new JTable();
        modelUpdate();
        table1.setModel(model);

        //listSelectionModel = table1.getSelectionModel();
        //table1.setSelectionModel(listSelectionModel);

        //table1.getModel().setValueAt();
        //dateTabel, columnNames
        ScrollPane = new JScrollPane(table1);
        //ScrollPane.add(table1);

        //table1=new JTable();
    }

    public void modelUpdate() {
        String[] columnNames = {"Id", "Descriere", "Cantitate", "Pret"};

        ListSelectionModel listSelectionModel;
        //JTableHeader=new JTableHeader()
        ProdusBLL produsBLL = new ProdusBLL();
        ArrayList<String[]> date;
        date = produsBLL.afiseazaProduse();

        model.setColumnNames(columnNames);
        model.setList(date);
        /*for (int i = 0; i < dateTabel.length; i++)
            for (int j = 0; j < columnNames.length; j++)
                model.setValueAt(dateTabel[i][j], i, j);*/


        //return model;
    }

    public JTable getTable1() {
        return table1;
    }

    public void setAdaugaInCosButton(ActionListener e) {
        this.adaugaInCosButton.addActionListener(e);
    }

    public JTextField getIdField() {
        return idField;
    }

    public JTextField getCantitateField() {
        return cantitateField;
    }

    public MyModel getModel() {
        return model;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(20, 10, 20, 10), -1, -1));
        panel1.setBackground(new Color(-5404120));
        ScrollPane.setBackground(new Color(-5404120));
        ScrollPane.setForeground(new Color(-5404120));
        panel1.add(ScrollPane, new GridConstraints(0, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table1.setAutoCreateRowSorter(false);
        table1.setBackground(new Color(-11225979));
        table1.setFillsViewportHeight(true);
        table1.setFont(new Font("Comic Sans MS", table1.getFont().getStyle(), 14));
        table1.putClientProperty("JTable.autoStartsEdit", Boolean.TRUE);
        table1.putClientProperty("Table.isFileList", Boolean.TRUE);
        table1.putClientProperty("html.disable", Boolean.FALSE);
        table1.putClientProperty("terminateEditOnFocusLost", Boolean.FALSE);
        ScrollPane.setViewportView(table1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-5404120));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Id Produs");
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Cantitate");
        panel2.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        adaugaInCosButton = new JButton();
        adaugaInCosButton.setBackground(new Color(-11225979));
        adaugaInCosButton.setFont(new Font("Comic Sans MS", adaugaInCosButton.getFont().getStyle(), 14));
        adaugaInCosButton.setText("Adauga in cos");
        panel2.add(adaugaInCosButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 15), new Dimension(200, 30), 0, false));
        cantitateField = new JTextField();
        panel2.add(cantitateField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 15), new Dimension(200, 30), 0, false));
        idField = new JTextField();
        panel2.add(idField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 15), new Dimension(200, 30), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
