package presentation;

import bll.ProdusBLL;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Created by Andrei on 21/04/2017.
 */
public class ListaProduse extends JFrame {
    private JTable table1;
    private JPanel panel1;
    private JScrollPane ScrollPane;
    private JButton adaugaInCosButton;
    private JTextField idField;
    private JTextField cantitateField;
    private JButton modificaButton;
    private JButton adaugaButon;
    private MyModel model;
    private String[] selectedData;
    private ListSelectionModel listSelectionModel;

    public ListaProduse() {
        model = new MyModel();
        table1 = new JTable();
        listSelectionModel = table1.getSelectionModel();
        table1.setSelectionModel(listSelectionModel);
        listSelectionModel.addListSelectionListener(new SharedListSelectionHandler());
        table1.setSelectionModel(listSelectionModel);
        $$$setupUI$$$();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setSize(380, 350);

        this.setLocationRelativeTo(null);
        this.setContentPane(panel1);
        this.setSize(600, 400);
        //adaugaInCosButton.addActionListener(new ButonAdaugaInCos());


        this.setResizable(false);
    }

    public void setModificaButton(ActionListener e) {
        modificaButton.addActionListener(e);
    }

    public void setAdaugaButton(ActionListener e) {
        adaugaButon.addActionListener(e);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        table1 = new JTable();
        modelUpdate();
        table1.setModel(model);
        table1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table1.add(table1.getTableHeader(), BorderLayout.PAGE_START);


        ScrollPane = new JScrollPane(table1);

    }

    public void modelUpdate() {
        String[] columnNames = {"Id", "Descriere", "Cantitate", "Pret"};


        ProdusBLL produsBLL = new ProdusBLL();
        ArrayList<String[]> date;
        date = produsBLL.afiseazaProduse();

        model.setColumnNames(columnNames);
        model.setList(date);

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 2, new Insets(20, 10, 20, 10), -1, -1));
        panel1.setBackground(new Color(-5404120));
        ScrollPane.setBackground(new Color(-5404120));
        ScrollPane.setForeground(new Color(-5404120));
        panel1.add(ScrollPane, new GridConstraints(0, 0, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table1.setBackground(new Color(-11225979));
        table1.setFillsViewportHeight(true);
        ScrollPane.setViewportView(table1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-5404120));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Id Produs");
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Cantitate");
        panel2.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        adaugaInCosButton = new JButton();
        adaugaInCosButton.setBackground(new Color(-11225979));
        adaugaInCosButton.setFont(new Font("Comic Sans MS", adaugaInCosButton.getFont().getStyle(), 14));
        adaugaInCosButton.setText("Adauga in cos");
        panel2.add(adaugaInCosButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 15), new Dimension(200, 30), 0, false));
        cantitateField = new JTextField();
        panel2.add(cantitateField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 15), new Dimension(200, 30), 0, false));
        idField = new JTextField();
        panel2.add(idField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 15), new Dimension(200, 30), 0, false));
        modificaButton = new JButton();
        modificaButton.setBackground(new Color(-11225979));
        modificaButton.setFont(new Font("Comic Sans MS", modificaButton.getFont().getStyle(), 14));
        modificaButton.setText("Modifica produs");
        panel2.add(modificaButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 15), new Dimension(200, 30), 0, false));
        adaugaButon = new JButton();
        adaugaButon.setBackground(new Color(-11225979));
        adaugaButon.setFont(new Font("Comic Sans MS", adaugaButon.getFont().getStyle(), 14));
        adaugaButon.setText("Adauga produs");
        panel2.add(adaugaButon, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 15), new Dimension(200, 30), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


    class SharedListSelectionHandler implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
            String contents = "";

            if (lsm.isSelectionEmpty()) {
                System.out.println("<none>");
            } else {
                int minIndex = lsm.getMinSelectionIndex();
                int maxIndex = lsm.getMaxSelectionIndex();
                if (minIndex == maxIndex) {
                    //minIndex++;
                    //System.out.println(minIndex);

                    setFields(minIndex);
                } else {
                    clearFields();
                    for (int i = minIndex; i <= maxIndex; i++) {
                        if (lsm.isSelectedIndex(i)) {
                            for (int j = 0; j < table1.getColumnCount(); j++) {
                                contents += table1.getValueAt(i, j) + " ";
                            }
                        }
                    }
                    System.out.println(contents);
                }
            }
        }
    }

    private void setFields(int index) {
        idField.setText(table1.getValueAt(index, 0).toString());
        // numar.setText(table.getValueAt(index, 5).toString());
        //year.setText(table.getValueAt(index, 2).toString());
    }

    private void clearFields() {
        idField.setText("");
        //color.setText("");
        //year.setText("");
    }

    public JTable getTable1() {
        return table1;
    }

    public void setAdaugaInCosButton(ActionListener e) {
        this.adaugaInCosButton.addActionListener(e);
    }

    public JTextField getIdField() {
        return idField;
    }

    public JTextField getCantitateField() {
        return cantitateField;
    }

    public MyModel getModel() {
        return model;
    }

}