package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * Created by Andrei on 20/04/2017.
 */
public class Logare extends JFrame {
    private JTextField parolaField;
    private JButton logareButton;
    private JTextField usernameField;
    private JPanel panelPrincipal;

    public Logare() {


        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setSize(350, 200);
        this.setLocationRelativeTo(null);
        this.setContentPane(panelPrincipal);
        this.setResizable(false);
        this.setVisible(true);

    }

    public void setLogareButton(ActionListener e) {
        logareButton.addActionListener(e);
    }


    public JTextField getUsernameField() {
        return usernameField;
    }


    public JTextField getParolaField() {
        return parolaField;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelPrincipal = new JPanel();
        panelPrincipal.setLayout(new GridLayoutManager(3, 2, new Insets(20, 10, 20, 10), 10, 10));
        panelPrincipal.setBackground(new Color(-5404120));
        panelPrincipal.setEnabled(true);
        panelPrincipal.setPreferredSize(new Dimension(350, 200));
        parolaField = new JTextField();
        parolaField.setFont(new Font("Comic Sans MS", parolaField.getFont().getStyle(), 14));
        panelPrincipal.add(parolaField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(500, 40), 0, false));
        final JLabel label1 = new JLabel();
        label1.setAlignmentX(0.5f);
        label1.setFont(new Font("Comic Sans MS", label1.getFont().getStyle(), 16));
        label1.setHorizontalTextPosition(10);
        label1.setText("Parola");
        panelPrincipal.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(50, 20), new Dimension(80, 20), new Dimension(200, 20), 0, false));
        final JLabel label2 = new JLabel();
        label2.setAlignmentX(0.5f);
        label2.setFont(new Font("Comic Sans MS", label2.getFont().getStyle(), 16));
        label2.setHorizontalTextPosition(10);
        label2.setText("Username");
        panelPrincipal.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(50, 20), new Dimension(90, 20), new Dimension(200, 20), 0, false));
        usernameField = new JTextField();
        usernameField.setFont(new Font("Comic Sans MS", usernameField.getFont().getStyle(), 14));
        panelPrincipal.add(usernameField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), new Dimension(500, 40), 0, false));
        logareButton = new JButton();
        logareButton.setBackground(new Color(-11225979));
        logareButton.setFont(new Font("Comic Sans MS", logareButton.getFont().getStyle(), 14));
        logareButton.setHorizontalAlignment(0);
        logareButton.setHorizontalTextPosition(0);
        logareButton.setText("Logare");
        panelPrincipal.add(logareButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(80, 20), new Dimension(100, 40), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelPrincipal;
    }
}
