package presentation;

import bll.CosBLL;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import model.Cos;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Andrei on 20/04/2017.
 */
public class Meniu extends JFrame {
    private JPanel panel1;
    private JButton cosNouButton;
    private JButton cosCurentButton;
    private JButton listaProduseButton;
    private JButton istoricCosuriButton;
    private JButton delogareButton;
    private JButton dateleTaleButton;

    public Meniu() {
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setSize(600, 400);
        this.setLocationRelativeTo(null);
        this.setContentPane(panel1);
        cosNouButton.addActionListener(new ButonCosNou());

        this.setResizable(false);
        //this.setVisible(true);
    }

    public void setDelogareButton(ActionListener e) {
        delogareButton.addActionListener(e);
    }

    public void setDateleTaleButton(ActionListener e) {
        dateleTaleButton.addActionListener(e);
    }

    public void setListaProduseButton(ActionListener e) {
        listaProduseButton.addActionListener(e);
    }

    public void setCosCurentButton(ActionListener e) {
        cosCurentButton.addActionListener(e);
    }

    public void setIstoricCosuriButton(ActionListener e) {
        istoricCosuriButton.addActionListener(e);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 20, 10), -1, -1));
        panel1.setBackground(new Color(-5404120));
        panel1.setMaximumSize(new Dimension(600, 400));
        panel1.setMinimumSize(new Dimension(500, 300));
        cosNouButton = new JButton();
        cosNouButton.setBackground(new Color(-11225979));
        Font cosNouButtonFont = this.$$$getFont$$$("Constantia", -1, 16, cosNouButton.getFont());
        if (cosNouButtonFont != null) cosNouButton.setFont(cosNouButtonFont);
        cosNouButton.setText("Cos nou");
        panel1.add(cosNouButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        cosCurentButton = new JButton();
        cosCurentButton.setBackground(new Color(-11225979));
        Font cosCurentButtonFont = this.$$$getFont$$$("Constantia", -1, 16, cosCurentButton.getFont());
        if (cosCurentButtonFont != null) cosCurentButton.setFont(cosCurentButtonFont);
        cosCurentButton.setText("Cos curent");
        panel1.add(cosCurentButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        listaProduseButton = new JButton();
        listaProduseButton.setBackground(new Color(-11225979));
        Font listaProduseButtonFont = this.$$$getFont$$$("Constantia", -1, 16, listaProduseButton.getFont());
        if (listaProduseButtonFont != null) listaProduseButton.setFont(listaProduseButtonFont);
        listaProduseButton.setText("Lista produse");
        panel1.add(listaProduseButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        istoricCosuriButton = new JButton();
        istoricCosuriButton.setBackground(new Color(-11225979));
        Font istoricCosuriButtonFont = this.$$$getFont$$$("Constantia", -1, 16, istoricCosuriButton.getFont());
        if (istoricCosuriButtonFont != null) istoricCosuriButton.setFont(istoricCosuriButtonFont);
        istoricCosuriButton.setText("Istoric cosuri");
        panel1.add(istoricCosuriButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 3, new Insets(10, 10, 20, 10), -1, -1));
        panel2.setBackground(new Color(-4112839));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        delogareButton = new JButton();
        delogareButton.setBackground(new Color(-11225979));
        Font delogareButtonFont = this.$$$getFont$$$("Constantia", -1, 16, delogareButton.getFont());
        if (delogareButtonFont != null) delogareButton.setFont(delogareButtonFont);
        delogareButton.setText("Delogare");
        panel2.add(delogareButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), new Dimension(200, 200), 0, false));
        dateleTaleButton = new JButton();
        dateleTaleButton.setBackground(new Color(-11225979));
        Font dateleTaleButtonFont = this.$$$getFont$$$("Constantia", -1, 16, dateleTaleButton.getFont());
        if (dateleTaleButtonFont != null) dateleTaleButton.setFont(dateleTaleButtonFont);
        dateleTaleButton.setText("Datele tale");
        panel2.add(dateleTaleButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), new Dimension(200, 200), 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Constantia", -1, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Bine ati venit!");
        panel2.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public class ButonCosNou implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            try {
                CosBLL cosBLL = new CosBLL();
                Cos cos = new Cos();
                cosBLL.insert(cos);

                JOptionPane.showMessageDialog(null, "A fost creat un cos nou!");

            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }


        }

    }


}
