package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * Created by Andrei on 20/04/2017.
 */
public class Meniu extends JFrame {
    private JPanel panel1;
    private JButton cosNouButton;
    private JButton cosCurentButton;
    private JButton listaProduseButton;
    private JButton istoricCosuriButton;
    private JButton delogareButton;
    private JButton dateleTaleButton;

    public Meniu() {
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setSize(600, 400);
        this.setLocationRelativeTo(null);
        this.setContentPane(panel1);

        this.setResizable(false);
        //this.setVisible(true);
    }

    public void setDelogareButton(ActionListener e)
    {
        delogareButton.addActionListener(e);
    }




    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 20, 10), -1, -1));
        panel1.setBackground(new Color(-5404120));
        panel1.setMaximumSize(new Dimension(600, 400));
        panel1.setMinimumSize(new Dimension(500, 300));
        cosNouButton = new JButton();
        cosNouButton.setBackground(new Color(-11225979));
        cosNouButton.setFont(new Font("Constantia", cosNouButton.getFont().getStyle(), 16));
        cosNouButton.setText("Cos nou");
        panel1.add(cosNouButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        cosCurentButton = new JButton();
        cosCurentButton.setBackground(new Color(-11225979));
        cosCurentButton.setFont(new Font("Constantia", cosCurentButton.getFont().getStyle(), 16));
        cosCurentButton.setText("Cos curent");
        panel1.add(cosCurentButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        listaProduseButton = new JButton();
        listaProduseButton.setBackground(new Color(-11225979));
        listaProduseButton.setFont(new Font("Constantia", listaProduseButton.getFont().getStyle(), 16));
        listaProduseButton.setText("Lista produse");
        panel1.add(listaProduseButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        istoricCosuriButton = new JButton();
        istoricCosuriButton.setBackground(new Color(-11225979));
        istoricCosuriButton.setFont(new Font("Constantia", istoricCosuriButton.getFont().getStyle(), 16));
        istoricCosuriButton.setText("Istoric cosuri");
        panel1.add(istoricCosuriButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(70, 60), new Dimension(200, 200), 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 3, new Insets(10, 10, 20, 10), -1, -1));
        panel2.setBackground(new Color(-4112839));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        delogareButton = new JButton();
        delogareButton.setBackground(new Color(-11225979));
        delogareButton.setFont(new Font("Constantia", delogareButton.getFont().getStyle(), 16));
        delogareButton.setText("Delogare");
        panel2.add(delogareButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), new Dimension(200, 200), 0, false));
        dateleTaleButton = new JButton();
        dateleTaleButton.setBackground(new Color(-11225979));
        dateleTaleButton.setFont(new Font("Constantia", dateleTaleButton.getFont().getStyle(), 16));
        dateleTaleButton.setText("Datele tale");
        panel2.add(dateleTaleButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 50), new Dimension(200, 200), 0, false));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font("Constantia", label1.getFont().getStyle(), 16));
        label1.setText("Bine ati venit!");
        panel2.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


}
